config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations', sessions: 'users/sessions'
  }
  root to: "home#index"

  resources :transactions
  resources :wallets
  resources :pins do
    collection do
      get :new
    end
  end
  resources :reloads
  resources :international_top_ups
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/international_top_up.rb
class InternationalTopUp < ApplicationRecord
  belongs_to :user
  validates :amount, :operator_id, :phone_number, presence: true
  enum status: [:pending, :failed, :success]

  def generate_ref_id
    largest_id = InternationalTopUp.all.map(&:ref_id).compact.max
    self.ref_id = if largest_id
                    largest_id + 1
                  else
                    1_000
                  end
  end
end

app/models/operator.rb
class Operator < ApplicationRecord
  has_many :transactions
  has_many :operator_pins
  has_many :operator_commissions
  has_many :operator_stores

  enum local_international: [:local, :international]
end

app/models/operator_commission.rb
class OperatorCommission < ApplicationRecord
  belongs_to :operator
end

app/models/operator_pin.rb
class OperatorPin < ApplicationRecord
  belongs_to :user
  validates :amount, :operator_id, presence: true
  enum status: [:pending, :success, :failed]
end

app/models/operator_store.rb
class OperatorStore < ApplicationRecord
  belongs_to :operator

  rails_admin do
    field :id
    field :operator do
      pretty_value do
        value.try(:operator_name)
      end
    end 
    field :amount
  end
end

app/models/reload.rb
class Reload < ApplicationRecord
  belongs_to :user
  enum status: [:pending, :success, :failed]
  enum transaction_type: [:cash_deposit, :online_transaction]
  validates :source, :amount, :transaction_type, :image,
            :reference_no, presence: true
  mount_uploader :image, ImageUploader
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  validates :amount, :operator_id, :phone_number, presence: true
  enum status: [:pending, :failed, :success]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :phone_number,
            presence: true,
            length: { maximum: 10 }

  has_many :transactions
  has_many :international_top_ups
  has_many :reloads
  has_many :operator_pins
  has_one :wallet
  after_create :create_wallet

  rails_admin do
    field :id
    field :name
    field :email
    field :phone_number
    field :created_at
  end

  def create_wallet
    WalletServices.new(self).init_wallet
  end

  def total_top_up_today
    transactions.where(
      'created_at BETWEEN ? AND ?',
      DateTime.now.beginning_of_day,
      DateTime.now.end_of_day).map(&:amount).sum
  end

  def total_pin_today
    operator_pins.where(
      'created_at BETWEEN ? AND ?',
      DateTime.now.beginning_of_day,
      DateTime.now.end_of_day).map(&:amount).sum
  end

  def total_international_today
    international_top_ups.where('created_at BETWEEN ? AND ?',
      DateTime.now.beginning_of_day,
      DateTime.now.end_of_day).map(&:amount).sum
  end

  def total_today
    total_top_up_today + total_pin_today + total_international_today
  end
end

app/models/user_pin.rb
class UserPin < ApplicationRecord
  
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit  
  protect_from_forgery with: :exception

  private

  def active_users_only
    redirect_to(new_user_session_path) && return unless user_signed_in?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/international_top_ups_controller.rb
class InternationalTopUpsController < ApplicationController
  before_action :active_users_only
  before_action :assign_international_operators
  
  def index; end

  def new
    @inter_top_up = InternationalTopUp.new
  end

  def create
    @inter_top_up = current_user.international_top_ups.build(tran_params)
    @inter_top_up.generate_ref_id
    if @inter_top_up.save
      InternationalTopUpServices.new(@inter_top_up).deduct_wallet
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def tran_params
    params.require(:international_top_up)
          .permit(:phone_number, :amount, :operator_id)
  end

  def assign_international_operators
    @operators = Operator.all.international
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :active_users_only
  before_action :assign_operators

  def new
    @pin = OperatorPin.new
  end

  def create
    @pin = current_user.operator_pins.build(pin_params)
    if @pin.save
      PinServices.new(@pin).deduct_wallet
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def pin_params
    params.require(:operator_pin).permit(:amount, :operator_id)
  end

  def assign_operators
    @operators = Operator.all
  end
end

app/controllers/reloads_controller.rb
class ReloadsController < ApplicationController
  before_action :active_users_only

  def new
    @reload = Reload.new
  end

  def create
    @reload = current_user.reloads.build(reload_params)
    if @reload.save
      ReloadServices.new(@reload).reload_check_bank
      redirect_to root_path
    else
      flash[:alert] = @reload.errors.full_messages.to_s
      render :new
    end
  end

  private

  def set_wallet
    @wallet = current_user.wallet.balance.to_i
  end

  def set_reload
    @reload_amount = current_user.reloads.success
  end

  def reload_params
    params.require(:reload)
          .permit(
            :source, :amount, :reference_no, :message,
            :image, :transaction_type
          )
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :active_users_only
  before_action :assign_operators
  before_action :check_wallet, only: [:create]

  def index; end

  def new
    @trx = Transaction.new
  end

  def create
    @trx = current_user.transactions.build(tran_params)
    if @trx.save
      TransactionServices.new(@trx).deduct_wallet
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def check_wallet
    return if balance > 10
    redirect_to new_transaction_path
    flash[:error] = 'Not Enough balance'
  end

  def tran_params
    params.require(:transaction)
          .permit(:phone_number, :amount, :commission, :operator_id)
  end

  def assign_operators
    @operators = Operator.all
  end

  def balance
    current_user.wallet.balance.to_i
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :active_users_only
  before_action :set_reloads_history, only: [:index]

  def new
    @wallet = Wallet.new
  end

  def create; end

  def index
    @wallet = current_user.wallet
  end

  private

  def wallet_params
    params.require(:wallet).permit(:user_id, :reference_id, :balance)
  end

  def set_reloads_history
    @reloads = current_user.reloads
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.haml
- provide :page_title, 'FoxPay Dashboard'
.row
  .col-12.col-md-4
    .card.shadow
      .card-block
        .card-title.text-center
          Today's Outlook
        .card-text
          .row.justify-content-center.my-3
            .btn.bg-purple.text-white.rounded-0
              = current_user.total_top_up_today if current_user.present?
          .row.justify-content-center.my-3
            .btn.bg-green.text-white.rounded-0
              = current_user.total_pin_today if current_user.present?
          .row.justify-content-center.my-3
            .btn.bg-red.text-white.rounded-0
              = current_user.total_international_today if current_user.present?
          .row.justify-content-center.my-3
            .btn.bg-red.text-white.rounded-0
              = current_user.total_today if current_user.present?
  .col-12.col-md-8
    .card.my-sm-0.mt-3
      .card-block
        .card-title.text-center
          FoxPay Live Chat
.row.mt-3
  .col-12.col-md-6.col-lg-4
    .card.my-sm-0.mt-3
      .card-block
        .card-title.text-center
          Local Top Up Status
        .card-text
          .row
            .col-6
              .row
                .col-6
                  = image_tag 'telcologo/hotlink.png', class: 'img-fluid max-50'
                .col-6
                  Online
            .col-6
              .row
                .col-6
                  = image_tag 'telcologo/umobile.png', class: 'img-fluid max-50'
                .col-6
                  Online
          .row
            .col-6
              .row
                .col-6
                  = image_tag 'telcologo/digi.png', class: 'img-fluid max-50'
                .col-6
                  Online
            .col-6
              .row
                .col-6
                  = image_tag 'telcologo/tunetalk.png', class: 'img-fluid max-50'
                .col-6
                  Online
          .row
            .col-6
              .row
                .col-6
                  = image_tag 'telcologo/onexox.png', class: 'img-fluid max-50'
                .col-6
                  Online
            .col-6
              .row
                .col-6
                  = image_tag 'telcologo/xpax.png', class: 'img-fluid max-50'
                .col-6
                  Online
  .col-12.col-md-6.col-lg-5
    .card.my-sm-0.mt-3
      .card-block
        .card-title.text-center
          My Monthly Commitment
        .card-text
          Graph Here
  .col-12.col-lg-3
    .card.my-lg-0.mt-3
      .card-block
        .card-title.text-center
          Monthly Ranking
        .card-text.text-left
          .d-block 1. Teset 5347
          .d-block 1. Teset 5347
          .d-block 1. Teset 5347
          .d-block 1. Teset 5347
          .d-block 1. Teset 5347
          .d-block 1. Teset 5347

app/views/pins/new.haml
- provide :page_title, 'PIN Purchase'
= simple_form_for @pin, url: pins_path do |f|
  .row
    .col-12
      .card
        .card-block
          .card-title Operator
          .card-text.text-center
            / = f.collection_radio_buttons :operator_id, @operators.map {|a| [a.id, a.operator_name ]}, :first, :last
            %div{'data-toggle':'buttons'}
              .btn.btn-hotlink.m-2
                %input{type: 'radio', name: 'test'}
              .btn.btn-digi.m-2
                %input{type: 'radio', name: 'test'}
              .btn.btn-umobile.m-2
                %input{type: 'radio', name: 'test'}
              .btn.btn-tunetalk.m-2
                %input{type: 'radio', name: 'test'}
              .btn.btn-onexox.m-2
                %input{type: 'radio', name: 'test'}
              .btn.btn-xpax.m-2
                %input{type: 'radio', name: 'test'}
  .row.mt-5
    .col-12
      .card
        .card-block
          .card-title Amount
          .card-text.text-center
            %div{'data-toggle':'buttons'}
              .btn.btn-radio.m-2
                %input{type: 'radio', name: 'test'}
                  .d-block RM
                  .d-block 5
              .btn.btn-radio.m-2
                %input{type: 'radio', name: 'test'}
                  .d-block RM
                  .d-block 10
              .btn.btn-radio.m-2
                %input{type: 'radio', name: 'test'}
                  .d-block RM
                  .d-block 15
              .btn.btn-radio.m-2
                %input{type: 'radio', name: 'test'}
                  .d-block RM
                  .d-block 20
              .btn.btn-radio.m-2
                %input{type: 'radio', name: 'test'}
                  .d-block RM
                  .d-block 30
              .btn.btn-radio.m-2
                %input{type: 'radio', name: 'test'}
                  .d-block RM
                  .d-block 50
              .btn.btn-radio.m-2.px-0
                %input{type: 'radio', name: 'test'}
                  .d-block RM
                  .d-block 100
  .row.mt-5.justify-content-center
    .btn.btn-red.m-2 Buy PIN
    = f.submit class: 'btn btn-red m-2'

app/views/transactions/_international_top_up.haml
%table.table.table-responsive.card
  %tr.card-block
    %td.align-middle Date-Time
    %td.align-middle Operator
    %td.align-middle Amount
    %td.align-middle Phone Number/PIN
    %td.align-middle Status
    %td.align-middle Status Reply
    %td.align-middle Commission
  -current_user.international_top_ups.each do |transaction|
    %tr.text-center
      %td.align-middle
        = transaction.created_at.to_date
      %td.align-middle
        = @operators.find(transaction.operator_id).operator_name
      %td.align-middle
        .btn.btn-radio.nofocus.px-0
          .d-block RM
          .d-block
            = transaction.amount
      %td.align-middle
        = transaction.phone_number
      %td.align-middle
        = transaction.status
      %td.align-middle
        = transaction.status_reply
      %td.align-middle
        = transaction.commission

app/views/transactions/_local_top_up.haml
%table.table.table-responsive.card
  %tr.card-block
    %td.align-middle Date-Time
    %td.align-middle Operator
    %td.align-middle Amount
    %td.align-middle Phone Number/PIN
    %td.align-middle Status
    %td.align-middle Status Reply
    %td.align-middle Commission
  -current_user.transactions.each do |transaction|
    %tr.text-center
      %td.align-middle
        = transaction.created_at.to_date
      %td.align-middle
        = @operators.find(transaction.operator_id).operator_name
      %td.align-middle
        .btn.btn-radio.nofocus.px-0
          .d-block RM
          .d-block
            = transaction.amount
      %td.align-middle
        = transaction.phone_number
      %td.align-middle
        = transaction.status
      %td.align-middle
        = transaction.status_reply
      %td.align-middle
        = transaction.commission

app/views/transactions/_pins.haml
%table.table.table-responsive.card
  %tr.card-block
    %td.align-middle Date-Time
    %td.align-middle Operator
    %td.align-middle Amount
    %td.align-middle PIN
    %td.align-middle Status

  -current_user.operator_pins.each do |transaction|
    %tr.text-center
      %td.align-middle
        = transaction.created_at.to_date
      %td.align-middle
        = @operators.find(transaction.operator_id).operator_name
      %td.align-middle
        .btn.btn-radio.nofocus.px-0
          .d-block RM
          .d-block
            = transaction.amount
      %td.align-middle
        = transaction.pins
      %td.align-middle
        = transaction.status

app/views/transactions/account.haml
- provide :page_title, 'My Account'
.row
  .col-12
    .card
      .card-block
        .card-text
          %p Name
          %p Registered Phone Number
          %p Email
      .card-block
        .card-text
          %p Username
          %p Password
          %p Confirm Password

app/views/transactions/agent_registration.haml
- provide :page_title, 'New Agent Registration'
.row
  .col-12
    .card
      .card-block
        .card-text
          %p Agent Name
          %p Business Phone Number
          %p Email
          Register

app/views/transactions/bill_payment.haml
- provide :page_title, 'Bill Payment'
.row
  .col-12
    .card
      .card-block
        .card-title Operator
        .card-text.text-center
          %div{'data-toggle':'buttons'}
            .btn.btn-hotlink.m-2
              %input{type: 'radio', name: 'test'}
            .btn.btn-digi.m-2
              %input{type: 'radio', name: 'test'}
            .btn.btn-umobile.m-2
              %input{type: 'radio', name: 'test'}
            .btn.btn-tunetalk.m-2
              %input{type: 'radio', name: 'test'}
            .btn.btn-onexox.m-2
              %input{type: 'radio', name: 'test'}
            .btn.btn-xpax.m-2
              %input{type: 'radio', name: 'test'}
.row.mt-5
  .col-12
    .card
      .card-block
        .card-title Amount
        .card-text.text-center
          %div{'data-toggle':'buttons'}
            .btn.btn-radio.m-2
              %input{type: 'radio', name: 'test'}
                .d-block RM
                .d-block 5
            .btn.btn-radio.m-2
              %input{type: 'radio', name: 'test'}
                .d-block RM
                .d-block 10
            .btn.btn-radio.m-2
              %input{type: 'radio', name: 'test'}
                .d-block RM
                .d-block 15
            .btn.btn-radio.m-2
              %input{type: 'radio', name: 'test'}
                .d-block RM
                .d-block 20
            .btn.btn-radio.m-2
              %input{type: 'radio', name: 'test'}
                .d-block RM
                .d-block 30
            .btn.btn-radio.m-2
              %input{type: 'radio', name: 'test'}
                .d-block RM
                .d-block 50
            .btn.btn-radio.m-2.px-0
              %input{type: 'radio', name: 'test'}
                .d-block RM
                .d-block 100
.row.mt-5.justify-content-center
  .btn.btn-red
    Pay Bill

app/views/transactions/help.haml
- provide :page_title, 'Video Tutorials'
.row
  .col-12.col-md-4
    .card.my-sm-0.mt-3
      = image_tag 'http://via.placeholder.com/350x200', class: 'img-fluid'
      .card-block
        .card-text
          How to register a new agent
  .col-12.col-md-4
    .card.my-sm-0.mt-3
      = image_tag 'http://via.placeholder.com/350x200', class: 'img-fluid'
      .card-block
        .card-text
          How to register a new agent
  .col-12.col-md-4
    .card.my-sm-0.mt-3
      = image_tag 'http://via.placeholder.com/350x200', class: 'img-fluid'
      .card-block
        .card-text
          How to register a new agent

app/views/transactions/history.haml
- provide :page_title, 'Transaction History'
.row
  .col-12
    %table.table.table-responsive.card
      %tr.card-block
        %td Date-Time
        %td Operator
        %td Amount
        %td Phone Number/PIN
        %td Status
        %td Status Reply
        %td Commission
    %table.table.table-responsive.card
      %tr.card-block
        %td Date-Time
        %td Operator
        %td Amount
        %td Phone Number/PIN
        %td Status
        %td Status Reply
        %td Commission
    %table.table.table-responsive.card
      %tr.card-block
        %td Date-Time
        %td Operator
        %td Amount
        %td Phone Number/PIN
        %td Status
        %td Status Reply
        %td Commission

app/views/transactions/index.haml
- provide :page_title, 'Transaction History'
.row
  .col-12
    = render 'local_top_up' if current_user.transactions.exists?
.row
  .col-12
    = render 'international_top_up' if current_user.international_top_ups.exists?
.row
  .col-12
    = render 'pins' if current_user.operator_pins.exists?
    -# %table.table.table-responsive.card
    -#   %tr.card-block
    -#     %td.align-middle Date-Time
    -#     %td.align-middle Operator
    -#     %td.align-middle Amount
    -#     %td.align-middle Phone Number/PIN
    -#     %td.align-middle Status
    -#     %td.align-middle Status Reply
    -#     %td.align-middle Commission
      -# -current_user.transactions.each do |transaction|
      -#   %tr.text-center
      -#     %td.align-middle
      -#       = transaction.created_at.to_date
      -#     %td.align-middle
      -#       = @operators.find(transaction.operator_id).operator_name
      -#     %td.align-middle
      -#       = transaction.amount
      -#     %td.align-middle
      -#       = transaction.phone_number
      -#     %td.align-middle
      -#       = transaction.status
      -#     %td.align-middle
      -#       = transaction.status_reply
      -#     %td.align-middle
      -#       = transaction.commission
      -# %tr.text-center
      -#   %td.align-middle
      -#     test
      -#   %td.align-middle
      -#     = image_tag 'telcologo/hotlink.png', class: 'img-fluid max-30'
      -#   %td.align-middle
      -#     .btn.btn-radio.nofocus.px-0
      -#       .d-block RM
      -#       .d-block 5
      -#   %td.align-middle
      -#     test
      -#   %td.align-middle
      -#     test
      -#   %td.align-middle
      -#     test
      -#   %td.align-middle
      -#     test
      -# %tr.text-center
      -#   %td.align-middle
      -#     test
      -#   %td.align-middle
      -#     = image_tag 'telcologo/umobile.png', class: 'img-fluid max-30'
      -#   %td.align-middle
      -#     .btn.btn-radio.nofocus.px-0
      -#       .d-block RM
      -#       .d-block 30
      -#   %td.align-middle
      -#     test
      -#   %td.align-middle
      -#     test
      -#   %td.align-middle
      -#     test
      -#   %td.align-middle
      -#     test
      -# %tr.text-center
      -#   %td.align-middle
      -#     test
      -#   %td.align-middle
      -#     = image_tag 'telcologo/digi.png', class: 'img-fluid max-30'
      -#   %td.align-middle
      -#     .btn.btn-radio.nofocus.px-0
      -#       .d-block RM
      -#       .d-block 10
      -#   %td.align-middle
      -#     test
      -#   %td.align-middle
      -#     test
      -#   %td.align-middle
      -#     test
      -#   %td.align-middle
      -#     test
      -# %tr.text-center
      -#   %td.align-middle
      -#     test
      -#   %td.align-middle
      -#     = image_tag 'telcologo/tunetalk.png', class: 'img-fluid max-30'
      -#   %td.align-middle
      -#     .btn.btn-radio.nofocus.px-0
      -#       .d-block RM
      -#       .d-block 100
      -#   %td.align-middle
      -#     test
      -#   %td.align-middle
      -#     test
      -#   %td.align-middle
      -#     test
      -#   %td.align-middle
      -#     test
      -# %tr.text-center
      -#   %td.align-middle
      -#     test
      -#   %td.align-middle
      -#     = image_tag 'telcologo/onexox.png', class: 'img-fluid max-30'
      -#   %td.align-middle
      -#     .btn.btn-radio.nofocus.px-0
      -#       .d-block RM
      -#       .d-block 20
      -#   %td.align-middle
      -#     test
      -#   %td.align-middle
      -#     test
      -#   %td.align-middle
      -#     test
      -#   %td.align-middle
      -#     test

app/views/transactions/international_top_up.haml
- provide :page_title, 'International Top Up'

= simple_form_for @trx, url: transactions_path do |f|
  .row
    .col-12
      .card
        .card-block
          .card-title Country
          
  .row
    .col-12
      .card
        .card-block
          .card-title Operator
          .card-text
            = f.label :operators
            = f.collection_radio_buttons :operator_id, @operators.international.map {|a| [a.id, a.operator_name ]}, :first, :last
  .row.mt-5
    .col-12
      .card
        .card-block
          .card-title Amount
          .card-text
            %input{type: 'radio', name: 'test'} 5
            %input{type: 'radio', name: 'test'} 10
            %input{type: 'radio', name: 'test'} 15
            %input{type: 'radio', name: 'test'} 20
            %input{type: 'radio', name: 'test'} 30
            %input{type: 'radio', name: 'test'} 50
  .row.mt-5
    .col-12
      .card
        .card-block
          .card-title Phone Number
          .card-text
            = f.input :phone_number
        = f.submit

app/views/transactions/local_top_up.haml
- provide :page_title, 'Local Top Up'
= simple_form_for @trx, url: transactions_path do |f|
  .row
    .col-12
      .card
        .card-block
          .card-title Operator
          .card-text
            = f.collection_radio_buttons :operator_id, @operators.local.map {|a| [a.id, a.operator_name ]}, :first, :last
  .row.mt-5
    .col-12
      .card
        .card-block
          .card-title Amount
          .card-text
            = f.input :amount
            %input{type: 'radio', name: 'test'} 5
            %input{type: 'radio', name: 'test'} 10
            %input{type: 'radio', name: 'test'} 15
            %input{type: 'radio', name: 'test'} 20
            %input{type: 'radio', name: 'test'} 30
            %input{type: 'radio', name: 'test'} 50
  .row.mt-5
    .col-12
      .card
        .card-block
          .card-title Phone Number
          .card-text
            = f.input :phone_number
          = f.submit

app/views/transactions/new.haml
- provide :page_title, 'Local Top Up'
= simple_form_for @trx, url: transactions_path do |f|
  .row
    .col-12
      .card
        .card-block
          .card-title Operator
          .card-text.text-center
            = f.collection_radio_buttons :operator_id, @operators, :id, :operator_name do |operator|
              = operator.label do
                = operator.radio_button
                = operator.object.operator_name
            -# - @operators.each do |a|
            -#   = f.input :operator_id, as: :radio_buttons 
            %div{'data-toggle':'buttons'}
              .btn.btn-hotlink.m-2
                %input{type: 'radio', name: 'test'}
              .btn.btn-digi.m-2
                %input{type: 'radio', name: 'test'}
              .btn.btn-umobile.m-2
                %input{type: 'radio', name: 'test'}
              .btn.btn-tunetalk.m-2
                %input{type: 'radio', name: 'test'}
              .btn.btn-onexox.m-2
                %input{type: 'radio', name: 'test'}
              .btn.btn-xpax.m-2
                %input{type: 'radio', name: 'test'}
  .row.mt-5
    .col-12
      .card
        .card-block
          .card-title Amount
          .card-text.text-center
            %div{'data-toggle':'buttons'}
              .btn.btn-radio.m-2
                %input{type: 'radio', name: 'test'}
                  .d-block RM
                  .d-block 5
              .btn.btn-radio.m-2
                %input{type: 'radio', name: 'test'}
                  .d-block RM
                  .d-block 10
              .btn.btn-radio.m-2
                %input{type: 'radio', name: 'test'}
                  .d-block RM
                  .d-block 15
              .btn.btn-radio.m-2
                %input{type: 'radio', name: 'test'}
                  .d-block RM
                  .d-block 20
              .btn.btn-radio.m-2
                %input{type: 'radio', name: 'test'}
                  .d-block RM
                  .d-block 30
              .btn.btn-radio.m-2
                %input{type: 'radio', name: 'test'}
                  .d-block RM
                  .d-block 50
              .btn.btn-radio.m-2.pt-0
                .d-block.mb-1 Other Amount
                %input.mw-7{type: 'text', name: 'test'}
  .row.mt-5
    .col-12
      .card
        .card-block
          .card-title Phone Number
          .card-text
            = f.input :amount
            = f.input :phone_number
          .text-center
            = f.submit class:'btn btn-red'