config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations', sessions: 'users/sessions'
  }
  root to: "home#index"

  resources :transactions
  resources :wallets
  resources :pins do
    collection do
      get :new
    end
  end
  resources :reloads
  resources :international_top_ups
end

app/models/reload.rb
class Reload < ApplicationRecord
  belongs_to :user
  enum status: [:pending, :success, :failed]
  enum transaction_type: [:cash_deposit, :online_transaction]
  validates :source, :amount, :transaction_type, :image,
            :reference_no, presence: true
  mount_uploader :image, ImageUploader
end

app/controllers/reloads_controller.rb
class ReloadsController < ApplicationController
  before_action :active_users_only

  def new
    @reload = Reload.new
  end

  def create
    @reload = current_user.reloads.build(reload_params)
    if @reload.save
      ReloadServices.new(@reload).reload_check_bank
      redirect_to root_path
    else
      flash[:alert] = @reload.errors.full_messages.to_s
      render :new
    end
  end

  private

  def set_wallet
    @wallet = current_user.wallet.balance.to_i
  end

  def set_reload
    @reload_amount = current_user.reloads.success
  end

  def reload_params
    params.require(:reload)
          .permit(
            :source, :amount, :reference_no, :message,
            :image, :transaction_type
          )
  end
end

app/views/reloads/new.html.haml
%h2 Reload

= simple_form_for @reload, url: reloads_path do |f|
  .row.mt-5
    .col-12
      .card
        .row
          .col-2
          .col-8
            = f.label :source
            = f.collection_radio_buttons :source,[['CIMB','CIMB'],['Bank Islam','Bank Islam']], :first, :last
        .row
          .col-2
          .col-8
            = f.label :transaction_type
            = f.collection_radio_buttons :transaction_type,[[:cash_deposit,'Cash Deposit'],[:online_transaction,'Online Transaction']], :first, :last
      .card.mt-5
        .row
          .col-2
          .col-8
            = f.input :amount
            = f.input :reference_no
      .card.mt-5 
        .row
          .col-2
          .col-8
            = f.label :image
        .row
          .col-2
          .col-8
            = f.file_field :image
      = f.submit