config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations', sessions: 'users/sessions'
  }
  root to: "home#index"

  resources :transactions
  resources :wallets
  resources :pins do
    collection do
      get :new
    end
  end
  resources :reloads
  resources :international_top_ups
end

app/models/international_top_up.rb
class InternationalTopUp < ApplicationRecord
  belongs_to :user
  validates :amount, :operator_id, :phone_number, presence: true
  enum status: [:pending, :failed, :success]

  def generate_ref_id
    largest_id = InternationalTopUp.all.map(&:ref_id).compact.max
    self.ref_id = if largest_id
                    largest_id + 1
                  else
                    1_000
                  end
  end
end

app/controllers/international_top_ups_controller.rb
class InternationalTopUpsController < ApplicationController
  before_action :active_users_only
  before_action :assign_international_operators
  
  def index; end

  def new
    @inter_top_up = InternationalTopUp.new
  end

  def create
    @inter_top_up = current_user.international_top_ups.build(tran_params)
    @inter_top_up.generate_ref_id
    if @inter_top_up.save
      InternationalTopUpServices.new(@inter_top_up).deduct_wallet
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def tran_params
    params.require(:international_top_up)
          .permit(:phone_number, :amount, :operator_id)
  end

  def assign_international_operators
    @operators = Operator.all.international
  end
end

app/views/international_top_ups/new.haml
- provide :page_title, 'International Top Up'

= simple_form_for @inter_top_up, url: international_top_ups_path do |f|
  .row
    .col-12
      .card
        .card-block
          .card-title Country

  .row
    .col-12
      .card.my-sm-0.mt-5
        .card-block
          .card-title Operator
          .card-text
            = f.label :operators
            = f.collection_radio_buttons :operator_id, @operators.map {|a| [a.id, a.operator_name ]}, :first, :last
  .row.mt-5
    .col-12
      .card
        .card-block
          .card-title Amount
          .card-text.text-center
            %div{'data-toggle':'buttons'}
              .btn.btn-radio.m-2
                %input{type: 'radio', name: 'test'}
                  .d-block RM
                  .d-block 5
              .btn.btn-radio.m-2
                %input{type: 'radio', name: 'test'}
                  .d-block RM
                  .d-block 10
              .btn.btn-radio.m-2
                %input{type: 'radio', name: 'test'}
                  .d-block RM
                  .d-block 15
              .btn.btn-radio.m-2
                %input{type: 'radio', name: 'test'}
                  .d-block RM
                  .d-block 20
              .btn.btn-radio.m-2
                %input{type: 'radio', name: 'test'}
                  .d-block RM
                  .d-block 30
              .btn.btn-radio.m-2
                %input{type: 'radio', name: 'test'}
                  .d-block RM
                  .d-block 50
              .btn.btn-radio.m-2.pt-0
                .d-block.mb-1 Other Amount
                %input.mw-7{type: 'text', name: 'test'}
                =f.input :amount
  .row.mt-5
    .col-12
      .card
        .card-block
          .card-title Phone Number
          .card-text
            = f.input :phone_number
          .text-center
            = f.submit class: 'btn btn-red'