config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations', sessions: 'users/sessions'
  }
  root to: "home#index"

  resources :transactions
  resources :wallets
  resources :pins do
    collection do
      get :new
    end
  end
  resources :reloads
  resources :international_top_ups
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/international_top_up.rb
class InternationalTopUp < ApplicationRecord
  belongs_to :user
  validates :amount, :operator_id, :phone_number, presence: true
  enum status: [:pending, :failed, :success]

  def generate_ref_id
    largest_id = InternationalTopUp.all.map(&:ref_id).compact.max
    self.ref_id = if largest_id
                    largest_id + 1
                  else
                    1_000
                  end
  end
end

app/models/operator.rb
class Operator < ApplicationRecord
  has_many :transactions
  has_many :operator_pins
  has_many :operator_commissions
  has_many :operator_stores

  enum local_international: [:local, :international]
end

app/models/operator_commission.rb
class OperatorCommission < ApplicationRecord
  belongs_to :operator
end

app/models/operator_pin.rb
class OperatorPin < ApplicationRecord
  belongs_to :user
  validates :amount, :operator_id, presence: true
  enum status: [:pending, :success, :failed]
end

app/models/operator_store.rb
class OperatorStore < ApplicationRecord
  belongs_to :operator

  rails_admin do
    field :id
    field :operator do
      pretty_value do
        value.try(:operator_name)
      end
    end 
    field :amount
  end
end

app/models/reload.rb
class Reload < ApplicationRecord
  belongs_to :user
  enum status: [:pending, :success, :failed]
  enum transaction_type: [:cash_deposit, :online_transaction]
  validates :source, :amount, :transaction_type, :image,
            :reference_no, presence: true
  mount_uploader :image, ImageUploader
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  validates :amount, :operator_id, :phone_number, presence: true
  enum status: [:pending, :failed, :success]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :phone_number,
            presence: true,
            length: { maximum: 10 }

  has_many :transactions
  has_many :international_top_ups
  has_many :reloads
  has_many :operator_pins
  has_one :wallet
  after_create :create_wallet

  rails_admin do
    field :id
    field :name
    field :email
    field :phone_number
    field :created_at
  end

  def create_wallet
    WalletServices.new(self).init_wallet
  end

  def total_top_up_today
    transactions.where(
      'created_at BETWEEN ? AND ?',
      DateTime.now.beginning_of_day,
      DateTime.now.end_of_day).map(&:amount).sum
  end

  def total_pin_today
    operator_pins.where(
      'created_at BETWEEN ? AND ?',
      DateTime.now.beginning_of_day,
      DateTime.now.end_of_day).map(&:amount).sum
  end

  def total_international_today
    international_top_ups.where('created_at BETWEEN ? AND ?',
      DateTime.now.beginning_of_day,
      DateTime.now.end_of_day).map(&:amount).sum
  end

  def total_today
    total_top_up_today + total_pin_today + total_international_today
  end
end

app/models/user_pin.rb
class UserPin < ApplicationRecord
  
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit  
  protect_from_forgery with: :exception

  private

  def active_users_only
    redirect_to(new_user_session_path) && return unless user_signed_in?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/international_top_ups_controller.rb
class InternationalTopUpsController < ApplicationController
  before_action :active_users_only
  before_action :assign_international_operators
  
  def index; end

  def new
    @inter_top_up = InternationalTopUp.new
  end

  def create
    @inter_top_up = current_user.international_top_ups.build(tran_params)
    @inter_top_up.generate_ref_id
    if @inter_top_up.save
      InternationalTopUpServices.new(@inter_top_up).deduct_wallet
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def tran_params
    params.require(:international_top_up)
          .permit(:phone_number, :amount, :operator_id)
  end

  def assign_international_operators
    @operators = Operator.all.international
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :active_users_only
  before_action :assign_operators

  def new
    @pin = OperatorPin.new
  end

  def create
    @pin = current_user.operator_pins.build(pin_params)
    if @pin.save
      PinServices.new(@pin).deduct_wallet
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def pin_params
    params.require(:operator_pin).permit(:amount, :operator_id)
  end

  def assign_operators
    @operators = Operator.all
  end
end

app/controllers/reloads_controller.rb
class ReloadsController < ApplicationController
  before_action :active_users_only

  def new
    @reload = Reload.new
  end

  def create
    @reload = current_user.reloads.build(reload_params)
    if @reload.save
      ReloadServices.new(@reload).reload_check_bank
      redirect_to root_path
    else
      flash[:alert] = @reload.errors.full_messages.to_s
      render :new
    end
  end

  private

  def set_wallet
    @wallet = current_user.wallet.balance.to_i
  end

  def set_reload
    @reload_amount = current_user.reloads.success
  end

  def reload_params
    params.require(:reload)
          .permit(
            :source, :amount, :reference_no, :message,
            :image, :transaction_type
          )
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :active_users_only
  before_action :assign_operators
  before_action :check_wallet, only: [:create]

  def index; end

  def new
    @trx = Transaction.new
  end

  def create
    @trx = current_user.transactions.build(tran_params)
    if @trx.save
      TransactionServices.new(@trx).deduct_wallet
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def check_wallet
    return if balance > 10
    redirect_to new_transaction_path
    flash[:error] = 'Not Enough balance'
  end

  def tran_params
    params.require(:transaction)
          .permit(:phone_number, :amount, :commission, :operator_id)
  end

  def assign_operators
    @operators = Operator.all
  end

  def balance
    current_user.wallet.balance.to_i
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :active_users_only
  before_action :set_reloads_history, only: [:index]

  def new
    @wallet = Wallet.new
  end

  def create; end

  def index
    @wallet = current_user.wallet
  end

  private

  def wallet_params
    params.require(:wallet).permit(:user_id, :reference_id, :balance)
  end

  def set_reloads_history
    @reloads = current_user.reloads
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flashes.html.haml
#flash-messages-container
  - flash.each do |k,v|
    %section.flash-messages
      %div{:class => "alert alert-#{k}"}
        %button#close.close{"data-dismiss" => "alert", :type => "button"}
          ×
        .message
          = v

app/views/layouts/_menu.haml
#mySidenav.sidenav.text-right.bg-red.py-5
  %h3.text-menu
    = link_to 'FoxPay', root_path, class: 'h-2-2 mt-3 text-white d-inline-block'
    = link_to 'Dashboard', root_path, class: 'h-2-2 mt-3 text-white d-block'
    = link_to 'Local Top Up', new_transaction_path, class: 'h-2-2 mt-3 text-white d-block'
    = link_to 'International Top Up', new_international_top_up_path, class: 'h-2-2 mt-3 text-white d-block'
    = link_to 'PIN', new_pin_path, class: 'h-2-2 mt-3 text-white d-block'
    = link_to 'Bill Payment', '', class: 'h-2-2 mt-3 text-white  d-block'
    = link_to 'Transactions History', transactions_path, class: 'h-2-2 mt-3 text-white d-block'
    = link_to 'E-Wallet',wallets_path, class: 'h-2-2 mt-3 text-white d-block'
    = link_to 'Wallet Reload',new_reload_path, class: 'h-2-2 mt-3 text-white d-block'
    = link_to 'My Account', '', class: 'h-2-2 mt-3 text-white d-block'
    = link_to 'Agent Registration', '', class: 'h-2-2 mt-3 text-white d-block'
    = link_to 'Help', '', class: 'h-2-2 mt-3 text-white d-block'
    = link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'h-2-2 mt-3 text-white d-block'

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta(name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no")
    %meta(name="mobile-web-app-capable" content="yes")
    %meta(name="apple-mobile-web-app-capable" content="yes")
    %title foxy
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body.bg-grey
    #main
      = render 'layouts/flashes'
      .container-fluid
        .row.full-height
          .col-1.bg-red.text-center.py-5.pr-xs-25.px-md-1
            = render 'layouts/menu'
            %span#toggler= icon('bars', class: 'h-2-2 mt-3 text-white fa-2x hidden-xs-down')
            = link_to root_path, class: 'text-deco-0' do
              = icon('tachometer', class: 'h-2-2 mt-3 ml-sm-minus-2 d-block text-white fa-2x')
              .span.text-white.mini-menu.text-truncate Dashboard
            = link_to new_transaction_path, class: 'text-deco-0' do
              = icon('caret-square-o-up', class: 'h-2-2 mt-3 ml-sm-minus-2 d-block text-white fa-2x')
              .span.text-white.mini-menu.text-truncate Local TopUp
            = link_to new_international_top_up_path, class: 'text-deco-0' do
              = icon('external-link', class: 'h-2-2 mt-3 ml-sm-minus-2 d-block text-white fa-2x')
              .span.text-white.mini-menu.text-truncate International TopUp
            = link_to new_pin_path, class: 'text-deco-0' do
              = icon('th', class: 'h-2-2 mt-3 ml-sm-minus-2 d-block text-white fa-2x')
              .span.text-white.mini-menu.text-truncate Pin
            = link_to '', class: 'text-deco-0' do
              = icon('file-text-o', class: 'h-2-2 mt-3 ml-sm-minus-2 d-block text-white fa-2x')
              .span.text-white.mini-menu.text-truncate Bill Payment
            = link_to transactions_path, class: 'text-deco-0' do
              = icon('history', class: 'h-2-2 mt-3 ml-sm-minus-2 d-block text-white fa-2x')
              .span.text-white.mini-menu.text-truncate Transaction History
            = link_to wallets_path, class: 'text-deco-0' do
              = icon('money', class: 'h-2-2 mt-3 ml-sm-minus-2 d-block text-white fa-2x')
              .span.text-white.mini-menu.text-truncate E-Wallet
            = link_to new_reload_path, class: 'text-deco-0' do
              = icon('money', class: 'h-2-2 mt-3 ml-sm-minus-2 d-block text-white fa-2x')
              .span.text-white.mini-menu.text-truncate Wallet Reload
            = link_to '', class: 'text-deco-0' do
              = icon('user', class: 'h-2-2 mt-3 d-block text-white fa-2x')
              .span.text-white.mini-menu.text-truncate My Account
            = link_to '', class: 'text-deco-0' do
              = icon('id-card-o', class: 'h-2-2 mt-3 ml-sm-minus-2 d-block text-white fa-2x')
              .span.text-white.mini-menu.text-truncate Agent Registration
            = link_to '', class: 'text-deco-0' do
              = icon('question', class: 'h-2-2 mt-3 d-block text-white fa-2x')
              .span.text-white.mini-menu.text-truncate Help
          .col-11.mw-xs-87
            .row.m-md-5.m-1
              .col
                .row.mb-3
                  .col-12.col-sm-8.text-left
                    .h1.text-main.font-weight-200= content_for :page_title
                  .col.text-right
                    = icon('usd', class: 'text-main fa-2x')
                    .btn.bg-red
                      .text-white.rounded-0
                        = current_user.wallet.balance if current_user.present? && current_user.wallet.balance?

                = yield
= content_for :extra_javascript
:javascript
  $(function() {
    $("#toggler").click(function(){
        $("#main").toggleClass("toggle-sidebar");
    });
  });